### PR TITLE
Initial implementation

### PR DESCRIPTION
**Pull request by slang25**
It's not very testable and it's all in one file 😆 But it's a start

### CODE REVIEW

**Comment by josephwoodward** [comment]
Nice! It's a first pass so as long as it works who cares if it's all in one file 😀

**Comment by slang25** [comment]
I could do with adding a check to see if the sdk is already installed by doing `dotnet --info`, but this will do for now.

**Comment by slang25** [comment]
I'm happy with this for now, let me know you think 😃

**Comment by josephwoodward** [comment]
> I could do with adding a check to see if the sdk is already installed by doing dotnet --info, but this will do for now.

Happy to do this.

**Comment by slang25** [comment]
@JosephWoodward that would be awesome 😃

**Comment by josephwoodward** [comment]
Well done on this, I've got a first version published here https://www.nuget.org/packages/InstallSdkGlobalTool/1.0.0-alpha

**Pull request merged**
